# Generated by Django 3.1.2 on 2020-11-04 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_headphones_turntable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turntable',
            name='category',
        ),
        migrations.DeleteModel(
            name='Headphones',
        ),
        migrations.DeleteModel(
            name='Turntable',
        ),
    ]
